### ISSUE TITLE
Go version not working anymore

### ISSUE THREAD

**Issue by rockyluke** [getmillipede/homebrew-millipede#2]
src/github.com/getmillipede/millipede-go/millipede.go:17:2: must be imported as github.com/Sirupsen/logrus
cmd/millipede-go/main.go:9:2: must be imported as github.com/codegangsta/cli
src/github.com/getmillipede/millipede-go/millipede.go:18:2: must be imported as github.com/kortschak/zalgo
src/github.com/getmillipede/millipede-go/millipede.go:19:2: must be imported as github.com/mgutz/ansi
src/github.com/getmillipede/millipede-go/vendor/github.com/kortschak/zalgo/zalgo.go:25:2: must be imported as golang.org/x/net/html
src/github.com/getmillipede/millipede-go/vendor/golang.org/x/net/html/node.go:8:2: must be imported as golang.org/x/net/html/atom

**Comment by moul** [comment]
Fixed
